### ISSUE TITLE
ERROR in deployment

### ISSUE THREAD

**Issue by sami5001** [vercel/virtual-event-starter-kit#105]
I am having issues with deploying the template. Could someone please help? This is the link to the repo:
[https://github.com/sami5001/HcAI-Design-Bootcamp-2024](https://github.com/sami5001/HcAI-Design-Bootcamp-2024)

The error that I get:
`Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /vercel/path0/node_modules/react/package.json`

**Comment by MarcoCrow99** [comment]
I get this error
Error: Node.js Version "14.x" is discontinued and must be upgraded. Please set "engines": { "node": "20.x" } in your `package.json` file to use Node.js 20.

**Comment by MarcoCrow99** [comment]
I updated my package.json to 20.x, and then I got same error saying to use 18.x. After doing that I now get the same error as OP 
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /vercel/path0/node_modules/react/package.json

**Comment by MarcoCrow99** [comment]
WTF VERCEL??????? this error is driving me crazy!

**Comment by MarcoCrow99** [comment]
Ok, obviously no one is monitoring this problem. Great.

**Comment by fullakingi** [comment]
I wanted to try this and was really interested but I got the same node error.  Iʻve subscribed to this issue, so incase someone from Vercel is able to please fix the dependencies issues I would be very grateful!  Thank you for this awesome repo.
🙏

**Comment by MarcoCrow99** [comment]
> For me it now worked after many trials.

What did you do to make it work?

**Comment by sami5001** [comment]
I searched in my IDE (pyCharm) for the error of the Node.js version , e.g. "14.x" and replaced it with what it was expecting, e.g. "20.x".
