### ISSUE TITLE
Installation with Prismic "Invalid theme provided"

### ISSUE THREAD

**Issue by cfofiu** [vercel/virtual-event-starter-kit#22]
I've been trying to install this with Prismic and I've been getting an "Invalid theme provided" error. I've tried to adjust the theme url but wasn't very successful.

```prismic theme --theme-url https://github.com/vercel/virtual-event-starter-kit/tree/prismic --conf lib/cms-providers/prismic/README.md --custom-types lib/cms-providers/prismic/custom_types --documents lib/cms-providers/prismic/documents```

**Comment by levimykel** [comment]
@cfofiu Thanks for bringing this up, I'm seeing the same thing. The theme url needs to be updated. This should work:

```
prismic theme --theme-url https://github.com/vercel/virtual-event-starter-kit/archive/main.zip --conf lib/cms-providers/prismic/README.md --custom-types lib/cms-providers/prismic/custom_types --documents lib/cms-providers/prismic/documents
```

I will get the instructions in the project updated with this.
