### ISSUE TITLE
Next JS Conf 2020 - Help

### ISSUE THREAD

**Issue by solomonshalom** [vercel/virtual-event-starter-kit#56]
Hey Developers,

Could you explain to me how to add the exact style like the one shown [here](https://vercel.com/virtual-event-starter-kit). Would be nice if anyone could help me on adding the rainbow color effect shown on the NextJS conf 2020 demo.

Thank You

**Comment by leerob** [comment]
Hey! You can inspect the CSS on the page to see the rainbow gradient used 😄
