### ISSUE TITLE
Issues launching headless chrome

### ISSUE THREAD

**Issue by smakosh** [vercel/virtual-event-starter-kit#70]
![image](https://user-images.githubusercontent.com/20082141/154802911-31f481e4-3a54-47bd-85d3-dc1d673e26e0.png)

**Comment by leerob** [comment]
Merged!

**Comment by thorwebdev** [comment]
@smakosh I'm running into this still :( what node.js version are you running?

**Comment by smakosh** [comment]
> @smakosh I'm running into this still :( what node.js version are you running?

14.*
