### ISSUE TITLE
Not Able to deploy this repo

### ISSUE THREAD

**Issue by Udit-takkar** [vercel/virtual-event-starter-kit#83]
I am getting request time out while i try to add datoCMS integration on vercel.

<img width="1440" alt="Screenshot 2022-03-16 at 5 55 09 PM" src="https://user-images.githubusercontent.com/53316345/158589531-8d127f0c-da60-4f54-8d9c-d4f6c698270c.png">

**Comment by piyush1104** [comment]
Hi @Udit-takkar, we have identified the issue. It happens for users having uppercase letters in their Github profile. For such errors, DatoCMS apis throws validation errors. We are tracking this internally and should be ready with a fix in few days. Will update you as soon as we fix this.

**Comment by Udit-takkar** [comment]
Okay

**Comment by guptakshi16** [comment]
@piyush1104 are there fixes required from datocms side ?

**Comment by piyush1104** [comment]
The proper fix for this is from DatoCMS side only. I have informed them and they have raised a ticket internally on their side. Meanwhile we will try to mitigate it from  our side also.

**Comment by CarlosLevir** [comment]
Hey @piyush1104, do you have any update about it?

**Comment by CarlosLevir** [comment]
It worked perfectly! Thank you @piyush1104!!

**Comment by CarlosLevir** [comment]
It seems like it's not working anymore, have you undone the changes @piyush1104?
