### ISSUE TITLE
Not allowing users to register

### ISSUE THREAD

**Issue by solomonshalom** [vercel/virtual-event-starter-kit#91]
I am unable to register in the virtual event starter kit, even after adding all the necessary environmental keys ->
![image](https://user-images.githubusercontent.com/71135230/180993720-76a786da-4a02-4df3-a08c-de8f1322a157.png)
I am not sure what the issue is @leerob or anybody who can help me out would be amazing!

**Comment by leerob** [comment]
Hey! It looks like you've forked this repo and changed some code. It's hard to tell what could be different in yours versus the template defined here. I'd recommend adding some logging and work backward for the errors.

**Comment by solomonshalom** [comment]
> Hey! It looks like you've forked this repo and changed some code. It's hard to tell what could be different in yours versus the template defined here. I'd recommend adding some logging and work backward for the errors.

Oh, I will check that out then because it isn't supposed to be that way, that's weird but thanks for the help!

**Comment by solomonshalom** [comment]
Hey @leerob I still can't register, even when I deployed a new project without changing a single piece of code.

**Comment by leerob** [comment]
Are your env variables right? We recently changed the name of the Redis env var.

**Comment by solomonshalom** [comment]
> Are your env variables right? We recently changed the name of the Redis env var.

@leerob Everything seems, right - haven't changed anything, tried registering, and still won't work. My repo - https://github.com/solomonshalom/virtual-event-starter-kit

**Comment by solomonshalom** [comment]
I think it's also affecting the other forks, when I checked them - I could be wrong though

**Comment by solomonshalom** [comment]
Hey @leerob I redid the project and it worked! Am not sure what I did but it works well. A small question - when I create a speaker through DatoCMS and click the speaker I created at the CMS, it shows up as a 404 error claiming a page like that does not exist. Does it take time to create a page? Or it's an error, am quite confused
