### ISSUE TITLE
Error With Repo

### ISSUE THREAD

**Issue by solomonshalom** [vercel/virtual-event-starter-kit#93]
Hi! Devs

I tried deploying this template to vercel and it worked! except when I tried registering - it didn't work at all. I am not sure what the issue is or if I need to set some things up, because it's not letting me register. I checked other forks and it seems that they are too facing it, not sure if it's because of the addition of superbase but it's really affecting a lot of users. I am currently relying on 100ms's fork of the virtual event starter kit as it was the only one that was working, please look into it as it's really affecting a lot of people @leerob @Deep-Codes @thorwebdev @chibicode 

Note - Unless there are any additional configs required to be done beforehand or any setup, it would be awesome if you guys can explain it :D

With Warm Regards,
Solomon Shalom Lijo

**Comment by thorwebdev** [comment]
@solomonshalom can you provide any screenshots of any error messages? That would be helpful!

**Comment by sami5001** [comment]
I am having issues with deploying the template. Could someone please help? This is the link to the repo: 
https://github.com/sami5001/HcAI-Design-Bootcamp-2024

The error that I get:
`Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /vercel/path0/node_modules/react/package.json`
